# Generated by Django 4.1.5 on 2023-01-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PL', 'Plants'), ('T', 'Tools'), ('FE', 'Fertilizers'), ('DCP', 'Disease Control Products'), ('FL', 'Flowers'), ('P', 'Pots')], max_length=5),
        ),
    ]
