# Generated by Django 4.1.4 on 2023-02-20 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_appointment_user_appointment_guser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='guser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
    ]
