# Generated by Django 4.1.4 on 2023-02-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_appointment_guser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='guser',
            new_name='user',
        ),
    ]
