# Generated by Django 4.1.5 on 2023-02-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prodapp',
        ),
    ]
