# Generated by Django 4.1.4 on 2023-03-09 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_appointment_customer_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='customer',
        ),
    ]
