# Generated by Django 4.1.4 on 2023-03-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_appointment_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='customer',
        ),
    ]
