# Generated by Django 4.1.4 on 2023-03-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_customer_city_alter_customer_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='locality',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.TextField(max_length=200),
        ),
    ]
