# Generated by Django 4.1.4 on 2023-03-24 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_customer_locality_alter_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,10}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
