# Generated by Django 4.1.4 on 2023-03-24 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_customer_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{6}$')]),
        ),
    ]
