# Generated by Django 4.1.4 on 2023-03-27 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_customer_locality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='locality',
            field=models.TextField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$')]),
        ),
    ]
